services:
  mysql:
    image: mysql:8.0
    container_name: app-obras-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_obras
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3307:3306" # si lo tenés ocupado, cambiá a "3307:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      # Opción simple: sin password
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  app-dev:
    build:
      context: .
      target: dev
    container_name: app-obras-dev
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma generate &&
        (npx prisma migrate deploy || npx prisma migrate dev --name init) &&
        npm run dev
      "


  app-prod:
    build:
      context: .
      target: prod
    container_name: app-obras
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start
      "

volumes:
  mysql_data:
  app_node_modules:
